//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TgBotFrame.Commands.Help.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TgBotFrame.Commands.Help.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на true\false.
        /// </summary>
        public static string BoolFormat {
            get {
                return ResourceManager.GetString("BoolFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на логический.
        /// </summary>
        public static string BoolName {
            get {
                return ResourceManager.GetString("BoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В данной категории находятся команды справки. Большинство из этих команд можно не вводить вручную, а использовать кнопки меню из комаанды help.
        /// </summary>
        public static string Category_Description_Help {
            get {
                return ResourceManager.GetString("Category_Description_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        public static string Category_Name_Help {
            get {
                return ResourceManager.GetString("Category_Name_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А.
        /// </summary>
        public static string CharFormat {
            get {
                return ResourceManager.GetString("CharFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на знак.
        /// </summary>
        public static string CharName {
            get {
                return ResourceManager.GetString("CharName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Команды.
        /// </summary>
        public static string CmdTitle {
            get {
                return ResourceManager.GetString("CmdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выводит главное меню справки.
        /// </summary>
        public static string Command_Description_Help {
            get {
                return ResourceManager.GetString("Command_Description_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выводит список команд из указанной категории.
        /// </summary>
        public static string Command_Description_HelpCategory {
            get {
                return ResourceManager.GetString("Command_Description_HelpCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выводит справку по команде.
        /// </summary>
        public static string Command_Description_HelpCommand {
            get {
                return ResourceManager.GetString("Command_Description_HelpCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выводит список категорий команд.
        /// </summary>
        public static string Command_Description_HelpList {
            get {
                return ResourceManager.GetString("Command_Description_HelpList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выводит справку по синтаксису команд.
        /// </summary>
        public static string Command_Description_HelpSyntax {
            get {
                return ResourceManager.GetString("Command_Description_HelpSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2000-12-24.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дата.
        /// </summary>
        public static string DateName {
            get {
                return ResourceManager.GetString("DateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2000-12-24T12:30.
        /// </summary>
        public static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дата и время.
        /// </summary>
        public static string DateTimeName {
            get {
                return ResourceManager.GetString("DateTimeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 05:30:00.
        /// </summary>
        public static string DurationFormat {
            get {
                return ResourceManager.GetString("DurationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на длительность.
        /// </summary>
        public static string DurationName {
            get {
                return ResourceManager.GetString("DurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.25.
        /// </summary>
        public static string FloatFormat {
            get {
                return ResourceManager.GetString("FloatFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дробное.
        /// </summary>
        public static string FloatName {
            get {
                return ResourceManager.GetString("FloatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Команды.
        /// </summary>
        public static string Help_Button_List {
            get {
                return ResourceManager.GetString("Help_Button_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат аргументов.
        /// </summary>
        public static string Help_Button_Syntax {
            get {
                return ResourceManager.GetString("Help_Button_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выводит справку по командам.
        /// </summary>
        public static string Help_Description {
            get {
                return ResourceManager.GetString("Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать в меню справки. Выберете необходимый пункт меню:.
        /// </summary>
        public static string HelpCommandController_Help_Title {
            get {
                return ResourceManager.GetString("HelpCommandController_Help_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тут собраны команды, не вошедшие ни в одну из категорий.
        /// </summary>
        public static string HelpCommandController_HelpCategory_NoCategory {
            get {
                return ResourceManager.GetString("HelpCommandController_HelpCategory_NoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория не найдена.
        /// </summary>
        public static string HelpCommandController_HelpCategory_NotFound {
            get {
                return ResourceManager.GetString("HelpCommandController_HelpCategory_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Команда не найдена.
        /// </summary>
        public static string HelpCommandController_HelpCommand_NotFound {
            get {
                return ResourceManager.GetString("HelpCommandController_HelpCommand_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Варианты:.
        /// </summary>
        public static string HelpCommandController_HelpCommand_Overloads {
            get {
                return ResourceManager.GetString("HelpCommandController_HelpCommand_Overloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберете категорию команд.
        /// </summary>
        public static string HelpCommandController_HelpList_Description {
            get {
                return ResourceManager.GetString("HelpCommandController_HelpList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступные категории команд:.
        /// </summary>
        public static string HelpCommandController_HelpList_Title {
            get {
                return ResourceManager.GetString("HelpCommandController_HelpList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (без категории).
        /// </summary>
        public static string HelpCommandController_HelpList_WithoutCategory {
            get {
                return ResourceManager.GetString("HelpCommandController_HelpList_WithoutCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Команды бота принимают два типа значений: команды и параметры\. Команда является идентификатором конкретного действия, которое должен совершить бот\. Идентификаторы команд не зависят от регистра: возможно использовать как строчные, так и заглавные буквы\. Параметрами являются данные необходимые для совершения действия\.
        ///
        ///Любая команда начинается с символа `/`; сразу после символа идет идентификатор команды\. Параметры разделяются между собой и идентификатором команды пробелами\. Например: на сообщение `/H [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string HelpCommandController_HelpSyntax_Title {
            get {
                return ResourceManager.GetString("HelpCommandController_HelpSyntax_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 123.
        /// </summary>
        public static string IntFormat {
            get {
                return ResourceManager.GetString("IntFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на целое.
        /// </summary>
        public static string IntName {
            get {
                return ResourceManager.GetString("IntName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @example.
        /// </summary>
        public static string MentionFormat {
            get {
                return ResourceManager.GetString("MentionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на упоминание.
        /// </summary>
        public static string MentionName {
            get {
                return ResourceManager.GetString("MentionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст.
        /// </summary>
        public static string TextFormat {
            get {
                return ResourceManager.GetString("TextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на текст.
        /// </summary>
        public static string TextName {
            get {
                return ResourceManager.GetString("TextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 15:30.
        /// </summary>
        public static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на время.
        /// </summary>
        public static string TimeName {
            get {
                return ResourceManager.GetString("TimeName", resourceCulture);
            }
        }
    }
}
