//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TgBotFrame.Commands.Authorization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TgBotFrame.Commands.Authorization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В выполнении команды отказано, вы не имеете необходимых ролей.
        /// </summary>
        public static string AuthorizationMiddleware_Denied {
            get {
                return ResourceManager.GetString("AuthorizationMiddleware_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь {0} заблокирован до {1:F}.
        /// </summary>
        public static string BanController_Ban_Result {
            get {
                return ResourceManager.GetString("BanController_Ban_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь {0} заблокирован навсегда.
        /// </summary>
        public static string BanController_Ban_ResultForever {
            get {
                return ResourceManager.GetString("BanController_Ban_ResultForever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без срока.
        /// </summary>
        public static string BanController_BanInfo_Infinite {
            get {
                return ResourceManager.GetString("BanController_BanInfo_Infinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У данного пользователя нет блокировок.
        /// </summary>
        public static string BanController_BanInfo_NotFound {
            get {
                return ResourceManager.GetString("BanController_BanInfo_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До .
        /// </summary>
        public static string BanController_BanInfo_Until {
            get {
                return ResourceManager.GetString("BanController_BanInfo_Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У пользователя нет активных блокировок.
        /// </summary>
        public static string BanController_UnBan_NotFound {
            get {
                return ResourceManager.GetString("BanController_UnBan_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь {0} разблокирован.
        /// </summary>
        public static string BanController_UnBan_Result {
            get {
                return ResourceManager.GetString("BanController_UnBan_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные команды позволяют управлять блокировками пользователей.
        /// </summary>
        public static string Category_Description_Ban {
            get {
                return ResourceManager.GetString("Category_Description_Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные команды позволяют управлять ролями, а также производить некоторые действия с их участниками, например, упоминать их.
        /// </summary>
        public static string Category_Description_Roles {
            get {
                return ResourceManager.GetString("Category_Description_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блокировки.
        /// </summary>
        public static string Category_Name_Ban {
            get {
                return ResourceManager.GetString("Category_Name_Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        public static string Category_Name_Roles {
            get {
                return ResourceManager.GetString("Category_Name_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приписывает к указанный роли пользователя.
        ///Сначала укажите название роли, а затем идентификатор пользователя..
        /// </summary>
        public static string Command_Description_AddRole {
            get {
                return ResourceManager.GetString("Command_Description_AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блокирует пользователя внутри бота, не позволяя ему исполнять команды. Различные варианты команды предполагают, что целым является идентификатор пользователя, длительность — время блокировки, а текст — описание причины блокировки для администраторов. Если время блокировки не указано, считается, что блокировка вечная..
        /// </summary>
        public static string Command_Description_Ban {
            get {
                return ResourceManager.GetString("Command_Description_Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отвечает списком заблокированных пользователей. Указав целым параметром идентификатор пользователя, бот отвечает подробностями блокировки.
        /// </summary>
        public static string Command_Description_BanInfo {
            get {
                return ResourceManager.GetString("Command_Description_BanInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите название роли первым аргументом, чтобы упомянуть всех участников роли. Вызвав команду без аргументов, бот ответит списком ролей, участников которых можно упомянуть. Вызывав команду с двумя аргументами, администраторы бота могут управлять возможностью упоминания роли.
        ///Первым аргументом является идентификатор роли, а вторым - признак возможности упоминания..
        /// </summary>
        public static string Command_Description_Mention {
            get {
                return ResourceManager.GetString("Command_Description_Mention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исключает пользователя из участников роли. 
        ///Сначала укажите название роли, а затем идентификатор пользователя..
        /// </summary>
        public static string Command_Description_RemoveRole {
            get {
                return ResourceManager.GetString("Command_Description_RemoveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Досрочно снимает блокировку у пользователя, чей идентификатор был указан.
        /// </summary>
        public static string Command_Description_UnBan {
            get {
                return ResourceManager.GetString("Command_Description_UnBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , ваша роль упомянута.
        /// </summary>
        public static string MentionController_Mention {
            get {
                return ResourceManager.GetString("MentionController_Mention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможность упоминания роли {0} теперь.
        /// </summary>
        public static string MentionController_Mention_EditResult {
            get {
                return ResourceManager.GetString("MentionController_Mention_EditResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможность упоминания участников ролей:.
        /// </summary>
        public static string MentionController_Mention_ListTitle {
            get {
                return ResourceManager.GetString("MentionController_Mention_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль не существует или в ней нет ни одного участника.
        /// </summary>
        public static string MentionController_Mention_NotFound {
            get {
                return ResourceManager.GetString("MentionController_Mention_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  **выключена** .
        /// </summary>
        public static string MentionController_Mention_Off {
            get {
                return ResourceManager.GetString("MentionController_Mention_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  *ВЫКЛ* .
        /// </summary>
        public static string MentionController_Mention_OffShort {
            get {
                return ResourceManager.GetString("MentionController_Mention_OffShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  **включена** .
        /// </summary>
        public static string MentionController_Mention_On {
            get {
                return ResourceManager.GetString("MentionController_Mention_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  **ВКЛ** .
        /// </summary>
        public static string MentionController_Mention_OnShort {
            get {
                return ResourceManager.GetString("MentionController_Mention_OnShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль &quot;{0}&quot; не существует.
        /// </summary>
        public static string RoleManagementController_Add_NotFound {
            get {
                return ResourceManager.GetString("RoleManagementController_Add_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователю {0} назначена роль &quot;{1}&quot;.
        /// </summary>
        public static string RoleManagementController_Add_Success {
            get {
                return ResourceManager.GetString("RoleManagementController_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователю {0} не назначена роль &quot;{1}&quot; или таковой не существует.
        /// </summary>
        public static string RoleManagementController_Remove_NotFound {
            get {
                return ResourceManager.GetString("RoleManagementController_Remove_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь {0} более не имеет роли &quot;{1}&quot;.
        /// </summary>
        public static string RoleManagementController_Remove_Success {
            get {
                return ResourceManager.GetString("RoleManagementController_Remove_Success", resourceCulture);
            }
        }
    }
}
