//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TgBotFrame.Commands.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TgBotFrame.Commands.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неоднозначный вызов команды &quot;{0}&quot;..
        /// </summary>
        public static string AmbiguousCall {
            get {
                return ResourceManager.GetString("AmbiguousCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 123.
        /// </summary>
        public static string ArgFormatText {
            get {
                return ResourceManager.GetString("ArgFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат аргументов.
        /// </summary>
        public static string ArgFormatTitle {
            get {
                return ResourceManager.GetString("ArgFormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аргументы.
        /// </summary>
        public static string ArgsTitle {
            get {
                return ResourceManager.GetString("ArgsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь заблокирован.
        /// </summary>
        public static string BanController_Ban_Result {
            get {
                return ResourceManager.GetString("BanController_Ban_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  **навсегда** .
        /// </summary>
        public static string BanController_Ban_Result_Forever {
            get {
                return ResourceManager.GetString("BanController_Ban_Result_Forever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  до .
        /// </summary>
        public static string BanController_Ban_Until {
            get {
                return ResourceManager.GetString("BanController_Ban_Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У пользователя нет активной блокировки.
        /// </summary>
        public static string BanController_UnBan_NotFound {
            get {
                return ResourceManager.GetString("BanController_UnBan_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С пользователя снята блокировка.
        /// </summary>
        public static string BanController_UnBan_Result {
            get {
                return ResourceManager.GetString("BanController_UnBan_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А.
        /// </summary>
        public static string CharFormat {
            get {
                return ResourceManager.GetString("CharFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на знак.
        /// </summary>
        public static string CharName {
            get {
                return ResourceManager.GetString("CharName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Команда не найдена..
        /// </summary>
        public static string CommandNotFoundMessage {
            get {
                return ResourceManager.GetString("CommandNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свяжитесь с администратором бота!.
        /// </summary>
        public static string ContactWithAdminMessage {
            get {
                return ResourceManager.GetString("ContactWithAdminMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2000-12-24.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дата.
        /// </summary>
        public static string DateName {
            get {
                return ResourceManager.GetString("DateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2000-12-24T12:30.
        /// </summary>
        public static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дата и время.
        /// </summary>
        public static string DateTimeName {
            get {
                return ResourceManager.GetString("DateTimeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 05:30:00.
        /// </summary>
        public static string DurationFormat {
            get {
                return ResourceManager.GetString("DurationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на длительность.
        /// </summary>
        public static string DurationName {
            get {
                return ResourceManager.GetString("DurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.25.
        /// </summary>
        public static string FloatFormat {
            get {
                return ResourceManager.GetString("FloatFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дробное.
        /// </summary>
        public static string FloatName {
            get {
                return ResourceManager.GetString("FloatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 123.
        /// </summary>
        public static string IntFormat {
            get {
                return ResourceManager.GetString("IntFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на целое.
        /// </summary>
        public static string IntName {
            get {
                return ResourceManager.GetString("IntName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат аргумента &quot;{0}&quot;..
        /// </summary>
        public static string InvalidArgFormatMessage {
            get {
                return ResourceManager.GetString("InvalidArgFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное количество аргументов..
        /// </summary>
        public static string InvalidArgsCountMessage {
            get {
                return ResourceManager.GetString("InvalidArgsCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @example.
        /// </summary>
        public static string MentionFormat {
            get {
                return ResourceManager.GetString("MentionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на упоминание.
        /// </summary>
        public static string MentionName {
            get {
                return ResourceManager.GetString("MentionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст.
        /// </summary>
        public static string TextFormat {
            get {
                return ResourceManager.GetString("TextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на текст.
        /// </summary>
        public static string TextName {
            get {
                return ResourceManager.GetString("TextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 15:30.
        /// </summary>
        public static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на время.
        /// </summary>
        public static string TimeName {
            get {
                return ResourceManager.GetString("TimeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Воспользуйтесь командой /help@{0} для получения справки.
        /// </summary>
        public static string UseHelpMessage {
            get {
                return ResourceManager.GetString("UseHelpMessage", resourceCulture);
            }
        }
    }
}
